// Generated by LispyScript v0.2.1
var dictionary = require("../lib/runtime").dictionary;

var rest = require("../lib/list").rest;

var readFromString = require("../lib/reader").readFromString;

var compileProgram = require("../lib/compiler").compileProgram;

var updatePreview = function(editor) {
  clearTimeout(updatePreview.id);
  return (function() {
    var code = editor.getValue();
    var source = ''.concat("(do ", code, ")");
    localStorage.buffer = code;
    return updatePreview.id = setTimeout(function() {
      return (function() {
        try {
          return (function() {
            editor.clearMarker((updatePreview.line || 1));
            return output.setValue(compileProgram(rest(readFromString(source))));
          })()
        } catch (error) {
          return (function() {
            updatePreview.line = error.line;
            return editor.setMarker(error.line, ''.concat("<span title='", error.message, "'>●</span> %N%"));
          })()
        };
      })();
    }, 200);
  })();
};

var input = CodeMirror(document.getElementById("input"), dictionary("lineNumbers", true, "autoClearEmptyLines:", true, "tabSize", 2, "indentWithTabs", false, "electricChars", true, "autoClearEmptyLines", true, "mode", "clojure", "theme", "ambiance", "autofocus", true, "fixedGutter", true, "matchBrackets", true, "value", (localStorage.buffer || (document.getElementById("examples")).innerHTML), "onChange", updatePreview, "onCursorActivity", function() {
  input.setLineClass(hlLine, null, null);
  return hlLine = input.setLineClass((input.getCursor()).line, null, "activeline");
}, "onGutterClick", function() {
  return (function() {
    var output = "output".getElementById();
    var input = "input".getElementById();
    output.hidden = !output.hidden;
    return input.style.width = output.hidden ?
      "100%" :
      "50%";
  })();
}));

var hlLine = input.setLineClass(0, "activeline");

var output = CodeMirror(document.getElementById("output"), dictionary("lineNumbers", true, "fixedGutter", true, "matchBrackets", true, "mode", "javascript", "theme", "ambiance", "readOnly", true));

setTimeout(updatePreview, 1000, input);

