// Generated by LispyScript v0.1.6
var fs = require("fs");
var ls = require((__dirname + "/ls"));
var repl = require((__dirname + "/repl"));
var readFileSyncOrExit = function(file) {
    return (function () {try {
        return fs.readFileSync(file);
    } catch (err) {return (function(err) {
        console.log(("Cannot open file " + file));
        return process.exit(1);
    })(err);}})();
};
var writeFileSyncOrExit = function(file,str) {
    return (function () {try {
        return fs.writeFileSync(file,str);
    } catch (err) {return (function(err) {
        console.log(("Cannot write file " + file));
        return process.exit(1);
    })(err);}})();
};
var compile = function(infile,outfile) {
    var source = readFileSyncOrExit(infile);
    var out = (function () {try {
        return ls._compile(source,infile);
    } catch (err) {return (function(err) {
        console.log(err);
        return process.exit(1);
    })(err);}})();
    return writeFileSyncOrExit(outfile,out);
};
exports.run = function() {
    return (process.argv.length === 2) ?
        repl.runrepl() : (process.argv.length === 3) ?
            (function() {
                var i = process.argv[2];
                var o = i.replace(".ls",".js");
                return (i === o) ?
                    console.log("Input file must have extension '.ls'") : compile(i,o);
            })() : compile(process.argv[2],process.argv[3]);
};
