// Generated by LispyScript v0.1.0
var fs = require("fs");
var path = require("path");
var ls = require((__dirname + "/ls"));
var repl = require((__dirname + "/repl"));
var compile = function(infile,outfile){var macrofile = (path.join(__dirname,"../src") + "/macros.ls");
var macros = fs.readFileSync(macrofile);
var source = fs.readFileSync(infile);
ls._compile(macros);
return fs.writeFileSync(outfile,ls._compile(source));
};
this.run = function(){return (process.argv.length === 2) ? repl.run() : (process.argv.length === 3) ? (function(){var i = process.argv[2];
var o = i.replace(".ls",".js");
return (i === o) ? console.log("Input file must have extension '.ls'") : compile(i,o);
})() : compile(process.argv[2],process.argv[3]);
};
