/*
LispyScript - Javascript using tree syntax!

Why use LispyScript?
1) It's fun.
2) Macros!

Here is hello world in LispyScript.
(console.log "Hello LispyScript!")

Defining a square function.
(var square
  (function (x)
    (* x x )))

Calling the function.
(square 9)

Every statement in LispyScript is a list enclosed in parenthesis. The first argument is a function,
or a LispyScript keyword like "var" and the rest are the function arguments.
  
1) Allowed characters in variable names are same as in Javascript.
2) In LispyScript the value returned by a function is the last expression evaluated by the function.
3) The var definition should not be the last statement in a function. Its redundant in any case. But
   your code will throw an error.
4) Macros must be defined in the top level. (Not inside functions).   
*/
// ToDo handle extra closing parenthesis at end. Comments.

var _LS = {};
_LS.version = "0.1.0";
_LS.gen = "// Generated by LispyScript v" + _LS.version + "\n";
_LS.tco = "var _tco = function(f) {var value, active = false, accumulated = [];recur = function() {accumulated.push(arguments);if (!active) {active = true;while (accumulated.length) value = f.apply(this, accumulated.shift());active = false;return value;};};return recur;};var recur;\n";
_LS.tconeeded = "";
_LS.whitespace = /\s/;
_LS.isFunction = /^function/;
_LS.varset = /^var|set\s/;
_LS.validName = /^[a-zA-Z_$][0-9a-zA-Z_$]*$/;
_LS.validFunction = /^[a-zA-Z_$][0-9a-zA-Z_$.]*$/;
_LS.macros = {};
_LS.indent = -4;

String.prototype.repeat = function( num ) {
    return new Array( num + 1 ).join( this );
}

_LS.syntaxTree = function(code) {
    if (/^\s*\(/.test(code) === false) throw _LS.error(0, 1);
    var code = "(" + code + ")";
    var length = code.length;
    var pos = 1;
    var lineno = 1;
    var parser = function() {
        var tree = [];
        tree._line = lineno;
        var token = "";
        var isString = false;
        var isSingleString = false;
        var isJSArray = 0;
        var isJSObject = 0;
        var isListComplete = false;
        var handleToken = function() {
            if (token) {
                tree.push(token);
                token = "";
            };
        };
        while (pos < length) {
            var c = code.charAt(pos);
            if (c == "\n") lineno++;
            pos++;
            if (c == '"') {
                isString = !isString;
                token += c;
                continue;
            };
            if (isString) {
                token += c;
                continue;
            };
            if (c == "'") {
                isSingleString = !isSingleString;
                token += c;
                continue;
            };
            if (isSingleString) {
                token += c;
                continue;
            };
            if (c == '[') {
                isJSArray++;
                token += c;
                continue;
            };
            if (c == ']') {
                if (isJSArray === 0) throw _LS.error(4, tree._line);
                isJSArray--;
                token += c;
                continue;
            };
            if (isJSArray) {
                token += c;
                continue;
            };
            if (c == '{') {
                isJSObject++;
                token += c;
                continue;
            };
            if (c == '}') {
                if (isJSObject === 0) throw _LS.error(6, tree._line);
                isJSObject--;
                token += c;
                continue;
            };
            if (isJSObject) {
                token += c;
                continue;
            };
            if (c == "(") {
                tree.push(parser());
                continue;
            };
            if (c == ")") {
                isListComplete = true;
                handleToken();
                break;
            };
            if (_LS.whitespace.test(c)) {
                handleToken();
                continue;
            };
            token += c;
        };
        if (isString) throw _LS.error(3, tree._line);
        if (isSingleString) throw _LS.error(3, tree._line);
        if (isJSArray > 0) throw _LS.error(5, tree._line);
        if (isJSObject > 0) throw _LS.error(7, tree._line);
        if (!isListComplete) throw _LS.error(8, tree._line);
        return tree;
    };
    var ret = parser();
    return ret;
};

_LS.expandObjects = function(tree) {
    for (var i = 0; i < tree.length; i++) {
        if (typeof tree[i] == "object") {
            tree[i] = _LS.statementToString(tree[i]);
        }
    };
    return tree;
};

_LS.macroExpand = function(tree) {
    var command = tree[0];
    var template = _LS.macros[command]["template"];
    var code = _LS.macros[command]["code"];
    var replacements = {};
    for (var i = 0; i < template.length; i++) {
        if (template[i] == "rest...") {
            replacements["~rest..."] = tree.slice(i + 1);
        } else {
            replacements["~" + template[i]] = tree[i + 1];
        }
    }
    var replaceCode = function(source) {
        var ret = [];
        ret._line = tree._line;
        for (var i = 0; i < source.length; i++) {
            if (typeof source[i] == "object") {
                ret.push(replaceCode(source[i]));
            } else {
                var token = source[i];
                var isATSign = false;
                if (token.indexOf("@") >= 0) {
                    isATSign = true;
                    token = token.replace("@", "") ;
                }
                if (replacements[token]) {
                    if (token === "~rest..." || isATSign) { 
                        ret = ret.concat(replacements[token]);
                    } else {
                        ret.push(replacements[token]);
                    }
                } else {                    
                    ret.push(token);
                }
            }
        }
        return ret;
    }
    var ret = replaceCode(code);
    return ret;
};

_LS.statementToString = function(tree) {
    var command = tree[0];
    if (_LS.macros[command]) {
        tree = _LS.macroExpand(tree);
        return _LS.statementToString(tree);
    }
    if (typeof command == "string") {
        if (command.charAt(0) == ".") {
            return "(" + _LS.statementToString(tree[1]) +")" + command;
        }
        if (_LS[command]) {
            return _LS[command](tree);
        }
    }
    tree = _LS.expandObjects(tree);
    var fName = tree[0];
    if (!fName) throw _LS.error(1, tree._line);
    if (fName === "_tco") _LS.tconeeded = _LS.tco;
//    if (!_LS.isFunction.test(fName))
//        if (!_LS.validFunction.test(fName)) {
//           console.log(fName);
//           throw _LS.error(2, tree._line);
//        }
    // testing for anonymous func called immediately
    if (_LS.isFunction.test(fName)) fName = "(" + fName + ")";
    return fName + "(" + tree.slice(1).join(",") + ")";
    
};

_LS.statements = function(stmnts) {
    _LS.indent += 4;
    var indent = " ".repeat(_LS.indent);
    var ret = "";
    var l = stmnts.length;
    for (var i = 0; i < l; i++) {
        var tmp;
        var r = "";
        if (i === l - 1 && _LS.indent) {
            t = stmnts[i][0];
            if (t !== "set" && t !== "var")
                r = "return "
        }
        if (typeof stmnts[i] === "object") {
            tmp = _LS.statementToString(stmnts[i]);
        } else {
            tmp = stmnts[i];
        }
        ret += indent + r + tmp + ";\n"
    }
    _LS.indent -= 4;
    return ret;
};

_LS.var = function(arr) {
    if (!_LS.validName.test(arr[1])) throw _LS.error(9, arr._line);
    return "var " + _LS.set(arr);
};

_LS.set = function(arr) {
    if (arr.length != 3) throw _LS.error(0, arr._line);
    var ret = arr[1] + " = ";
    if (typeof arr[2] == "object") {
       ret += _LS.statementToString(arr[2]);
    } else {
       ret += arr[2];
    }
    return ret;
}

_LS.get = function(arr) {
    if (arr.length != 3) throw _LS.error(0, arr._line);
    return arr[2] + "[" + arr[1] + "]";
};

_LS.function = function(arr) {
    if (arr.length < 3) throw _LS.error(0, arr._line);
    if (typeof arr[1] != "object") throw _LS.error(0, arr._line);
    var ret = "function(" + arr[1].join(",") + "){\n";
    ret += _LS.statements(arr.slice(2), true);
    ret += " ".repeat(_LS.indent) + "}";
    return ret;
}

_LS.try = function(arr) {
    if (arr.length < 3) throw _LS.error(0, arr._line);
    var c = arr.pop();
    var ret = "(function () {try {\n" + _LS.statements(arr.slice(1), true) + 
              " ".repeat(_LS.indent) + "} catch (err) {(" + _LS.statementToString(c) + ")(err)}})()"
    return ret;
}

_LS.if = function(arr) {
    if (arr.length < 3 || arr.length > 4)  throw _LS.error(0, arr._line);
    _LS.indent += 4;
    arr = _LS.expandObjects(arr);
    var ret = arr[1] + " ?\n" + " ".repeat(_LS.indent) + arr[2] + " :\n" + " ".repeat(_LS.indent) + arr[3];
    _LS.indent -= 4;
    return ret;
}

_LS.handleOperator = function(arr) {
    if (arr.length != 3)  throw _LS.error(0, arr._line);
    arr = _LS.expandObjects(arr);
    return "(" + arr[1] + " " + arr[0] + " " + arr[2] + ")";    
};

_LS["+"] = _LS.handleOperator;

_LS["-"] = _LS.handleOperator;

_LS["*"] = _LS.handleOperator;

_LS["/"] = _LS.handleOperator;

_LS["%"] = _LS.handleOperator;

_LS["="] = function(arr) {
    if (arr.length != 3)  throw _LS.error(0, arr._line);
    arr = _LS.expandObjects(arr);
    return "(" + arr[1] + " === " + arr[2] + ")";
}

_LS["!="] = function(arr) {
    if (arr.length != 3)  throw _LS.error(0, arr._line);
    arr = _LS.expandObjects(arr);
    return "(" + arr[1] + " !== " + arr[2] + ")";
}

_LS[">"] = _LS.handleOperator;

_LS[">="] = _LS.handleOperator;

_LS["<"] = _LS.handleOperator;

_LS["<="] = _LS.handleOperator;

_LS["||"] = _LS.handleOperator;

_LS["&&"] = _LS.handleOperator;

_LS["!"] = function(arr) {
    if (arr.length != 2)  throw _LS.error(0, arr._line);
    arr = _LS.expandObjects(arr);
    return "(!" + arr[1] + ")";
}

_LS.macro = function(arr) {
    if (arr.length != 4)  throw _LS.error(0, arr._line);
    _LS.macros[arr[1]] = {template: arr[2], code: arr[3]};
    return null;
}

_LS.error = function(no, line) {
    return _LS.err[no] + ", line no " + line;
}
_LS.err = [];
_LS.err[0] = "Syntax Error";
_LS.err[1] = "Empty statement";
_LS.err[2] = "Invalid characters in function name";
_LS.err[3] = "End of File encountered, unterminated string";
_LS.err[4] = "Closing square bracket, without an opening square bracket";
_LS.err[5] = "End of File encountered, unterminated array";
_LS.err[6] = "Closing curly brace, without an opening curly brace";
_LS.err[7] = "End of File encountered, unterminated javascript object '}'";
_LS.err[8] = "End of File encountered, unterminated parenthesis";
_LS.err[9] = "Invalid character in var name";

this.version = _LS.version;

this._compile = function(code) {
  var tree = _LS.syntaxTree(code);
  var gen = _LS.statements(tree);
  return _LS.gen +  _LS.tconeeded + gen;
}
