// Generated by LispyScript v0.2.1
require("amd-loader");

var fs = require("fs");

var ls = require("../lib/ls");

require.extensions[".ls"] = function(module, filename) {
  var code = fs.readFileSync(filename, "utf8");
  return module._compile(ls._compile(code, filename), filename);
};

require("../src/macros");

