// Generated by LispyScript v0.1.0
(function() {
var _tco = function(f) {var value, active = false, accumulated = [];recur = function() {accumulated.push(arguments);if (!active) {active = true;while (accumulated.length) value = f.apply(this, accumulated.shift());active = false;return value;};};return recur;};var recur;
var readline = require("readline");
var ls = require((__dirname + "/ls"));
var handleLine = function(line){return console.log(line);
};
var handleClose = function(){console.log("Bye!");
return process.exit(0);
};
exports.runrepl = function(){var rl = readline.createInterface(process.stdin,process.stdout);
rl.on('line',handleLine);
rl.on('close',handleClose);
var prefix = "lispy> ";
console.log(((prefix + 'LispyScript REPL v') + ls.version));
rl.setPrompt(prefix,prefix.length);
return rl.prompt();
};
})();