// Generated by LispyScript v0.1.0
var readline = require("readline");
var ls = require((__dirname + "/ls"));
var prefix = "lispy> ";
exports.runrepl = function() {
    var rl = readline.createInterface(process.stdin,process.stdout);
    rl.on('line',function(line) {
        (function () {try {
            var l = ls._compile(line);
            return console.log(eval(l));
        } catch (err) {return (function(err) {
            return console.log(err);
        })(err);}})();
        rl.setPrompt(prefix,prefix.length);
        return rl.prompt();
    });
    rl.on('close',function() {
        console.log("Bye!");
        return process.exit(0);
    });
    console.log((function() {
        return (Array.prototype.slice.call(arguments)).join("");
    })(prefix,'LispyScript REPL v',ls.version));
    rl.setPrompt(prefix,prefix.length);
    return rl.prompt();
};
