// Generated by LispyScript v0.1.0
var fib = function(n){return (function(a,b,count){var recur = arguments.callee;
return (count === 0) ? b : recur((a + b),a,(count - 1));
})(1,0,n);
};
console.log(fib(10));
