// Generated by LispyScript v0.1.0
var http = require("http");
(http.createServer(function(req,res){
    res.writeHead(200,{'Content-Type': 'text/plain'});
    return res.end("Hello World\n");
})).listen(1337,"127.0.0.1");
console.log("Server running at http://127.0.0.1:1337/");
