// Generated by LispyScript v0.1.0
console.log("starting tests..");
var square = function(n) {
    return (n * n);
};
console.log(square(10));
(function () {try {
    console.log("In try");
    throw("In catch");
} catch (err) {return (function(err) {
    return console.log(err);
})(err);}})();
(typeof(window) === "undefined") ?
    console.log("Not Running on browser") : console.log("Running on browser");
var arr = [1, 2, 3, 4, 5];
console.log(arr[2]);
(1 !== 2) ?
    console.log("Nos are not equal") : undefined;
(typeof("ss") === "object") ?
    console.log("This is an ob1") : console.log("Not an obj");
(toString.call(console) === "[object Array]") ?
    console.log("This is an array") : console.log("Not an array");
console.log((10 * 10));
var i = 2;
console.log((i++ * i++));
var _ = require('underscore');
Array.prototype.forEach.call([1, 2, 3],function(elem,i,list) {
    return console.log(elem);
});
(function(name,email,tel) {
    console.log(name);
    return console.log(email);
})("John","john@example.com","555-555-5556");
(function() {
    console.log("testing do");
    return console.log("test again");
})();
console.log((function() {
    return (Array.prototype.slice.call(arguments)).join("");
})("Hello1"," world1"));
var title = "TITLE";
console.log((function() {
    return (Array.prototype.slice.call(arguments)).join("");
})("<!DOCTYPE html>\n","<html>\n","<head>\n","  <title>",title,"</title>\n","</head>\n","<body>\n","Hello World\n","</body>\n","</html>\n"));
(function(name,email,tel) {
    console.log(name);
    return console.log(email);
})("John","john@example.org","555-555-5555");
