// Generated by LispyScript v0.1.0
var test = (function(fn,arr,count,accum){var recur = arguments.callee;
return (count === arr.length) ? accum : recur(fn,arr,(count + 1),fn(arr,arr[count],count,accum));
})(function(arr,item,count,accum){(accum === null) ? accum = [] : undefined;
accum.push((function(x){return (x + 2);
})(item));
return accum;
},[1, 2, 3, 4],0,null);
console.log(test);
