// Generated by LispyScript v0.1.0
console.log("starting tests..");
var square = function(n) {
    return (n * n);
};
console.log(square(10));
(function () {try {
    console.log("In try");
    throw("In catch");
} catch (err) {(function(err) {
    return console.log(err);
})(err)}})();
(typeof(window) === "object") ?
    console.log("Running on browser") 
    : console.log("Not Running on browser");
var arr = [1, 2, 3, 4, 5];
console.log(arr[2]);
(1 !== 2) ?
    console.log("Nos are not equal") 
    : undefined;
